# Generated by Django 4.2.11 on 2024-03-19 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import monitoring.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dalolatnoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('huquqbuzar_turi', models.CharField(choices=[('jismoniy', 'Jismoniy shaxs'), ('yuridik', 'Yuridik shaxs')], max_length=25)),
                ('huquqbuzar_nomi', models.CharField(max_length=255)),
                ('huquqbuzar_stir', models.CharField(max_length=100)),
                ('orientir', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=11)),
                ('lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('korsatma_raqam', models.CharField(max_length=100)),
                ('korsatma_sana', models.DateTimeField()),
                ('korsatma_rasm_qogoz', models.ImageField(upload_to=monitoring.models.Dalolatnoma.kr_qogoz)),
                ('korsatma_rasm_odam', models.ImageField(upload_to=monitoring.models.Dalolatnoma.kr_odam)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspektor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Noqonuniy_holat_turi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stansiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Viloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('viloyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.viloyat')),
            ],
        ),
        migrations.CreateModel(
            name='DalolatnomaRasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to=monitoring.models.DalolatnomaRasm.photo_location)),
                ('dalolatnoma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.dalolatnoma')),
            ],
        ),
        migrations.AddField(
            model_name='dalolatnoma',
            name='noqonuniy_holat_turi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.noqonuniy_holat_turi'),
        ),
        migrations.AddField(
            model_name='dalolatnoma',
            name='stansiya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.stansiya'),
        ),
        migrations.AddField(
            model_name='dalolatnoma',
            name='tuman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.tuman'),
        ),
    ]
