# Generated by Django 4.2.11 on 2024-04-16 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dalolatnoma',
            name='amal_qilish_muddati',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='dalolatnoma',
            name='bartaraf_etilganligi',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
