# Generated by Django 4.2.11 on 2024-04-24 05:04

from django.db import migrations, models
import monitoring.models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alter_dalolatnoma_korsatma_raqam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dalolatnoma',
            options={'verbose_name': 'Dalolatnoma', 'verbose_name_plural': 'Dalolatnomalar'},
        ),
        migrations.AlterModelOptions(
            name='noqonuniy_holat_turi',
            options={'verbose_name': 'Noqonuniy holat turi', 'verbose_name_plural': 'Noqonuniy holat turi'},
        ),
        migrations.AlterModelOptions(
            name='stansiya',
            options={'verbose_name': 'Stansiya', 'verbose_name_plural': 'Stansiyalar'},
        ),
        migrations.AlterModelOptions(
            name='tuman',
            options={'verbose_name': 'Tuman', 'verbose_name_plural': 'Tumanlar'},
        ),
        migrations.AlterModelOptions(
            name='viloyat',
            options={'verbose_name': 'Viloyat', 'verbose_name_plural': 'Viloyatlar'},
        ),
        migrations.AddField(
            model_name='dalolatnoma',
            name='bartaraf_etilganligi_hujjati',
            field=models.FileField(blank=True, null=True, upload_to=monitoring.models.Dalolatnoma.brt_hujjat),
        ),
        migrations.AddField(
            model_name='stansiya',
            name='seriya',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
