# Generated by Django 4.2.11 on 2025-04-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_dalolatnoma_maqsadi_dalolatnoma_miqdori'),
    ]

    operations = [
        migrations.AddField(
            model_name='stansiya',
            name='soni',
            field=models.IntegerField(default=0),
        ),
    ]
